language: python
sudo : required
python:
  - 2.7
install:
  - sudo pip install -r requirements.txt
  - sudo apt-get install coreutils
  - which env
  - ls /usr/lib/python2.7/dist-packages/dateutil/__init__.py
script:
  - nosetests test
